version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  api-gateway:
    build: ./APIGateway
    ports:
      - "7000:7000"
    depends_on:
      - mongodb

  front:
    build: ./Front
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  gestion-freezbe:
    build: ./MicroService/GestionFreezbe
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  users:
    build: ./MicroService/Users
    ports:
      - "9000:9000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
